---
title: "HomeWork 3"
author: "Swarupa Vaishampayan"
date: "February 23, 2018"
output: html_document
---

```{r}
library(MASS) # for the example dataset 
library(plyr) # for recoding data
library(ROCR) # for plotting roc
library(e1071) # for NB and SVM
library(rpart) # for decision tree
library(ada) # for adaboost
library(ggplot2)
library(cvTools)
library(car)
library(class)
```


```{r}
set.seed(23468)
do.classification <- function(train.set, test.set, 
                              cl.name, verbose=F) {
  ## note: to plot ROC later, we want the raw probabilities,
  ## not binary decisions
  switch(cl.name, 
         knn = { # here we test k=3; you should evaluate different k's
           prob = knn(train.set[,-1], test.set[,-1], cl=train.set$Total, k = 3, prob=T)
           prob = attr(prob,"prob")
           #print(cbind(prob,as.character(test.set$y)))
           prob
         },
         lr = { # logistic regression
           model = glm(Total~., family=binomial, data=train.set)
           if (verbose) {
             print(summary(model))             
           }
           prob = predict(model, newdata=test.set, type="response") 
           #print(cbind(prob,as.character(test.set$y)))
           prob
         },
         nb = {
           model = naiveBayes(Total~., data=train.set)
           prob = predict(model, newdata=test.set, type="raw") 
           #print(cbind(prob,as.character(test.set$y)))
           prob = prob[,2]/rowSums(prob) # renormalize the prob.
           prob
         },
         dtree = {
           model = rpart(Total~., data=train.set)
           if (verbose) {
             print(summary(model)) # detailed summary of splits
             printcp(model) # print the cross-validation results
             plotcp(model) # visualize the cross-validation results
             ## plot the tree
             plot(model, uniform=TRUE, main="Classification Tree")
             text(model, use.n=TRUE, all=TRUE, cex=.8)
           }           
           prob = predict(model, newdata=test.set)
           
           if (0) { # here we use the default tree, 
             ## you should evaluate different size of tree
             ## prune the tree 
             pfit<- prune(model, cp=model$cptable[which.min(model$cptable[,"xerror"]),"CP"])
             prob = predict(pfit, newdata=test.set)
             ## plot the pruned tree 
             plot(pfit, uniform=TRUE,main="Pruned Classification Tree")
             text(pfit, use.n=TRUE, all=TRUE, cex=.8)             
           }
           #print(cbind(prob,as.character(test.set$y)))
           prob = prob[,2]/rowSums(prob) # renormalize the prob.
           prob
         },
         svm = {
           model = svm(Total~., data=train.set, probability=T)
           if (0) { # fine-tune the model with different kernel and parameters
             ## evaluate the range of gamma parameter between 0.000001 and 0.1
             ## and cost parameter from 0.1 until 10
             tuned <- tune.svm(Total~., data = train.set, 
                               kernel="radial", 
                               gamma = 10^(-6:-1), cost = 10^(-1:1))
             #print(summary(tuned))
             gamma = tuned[['best.parameters']]$gamma
             cost = tuned[['best.parameters']]$cost
             model = svm(Total~., data = train.set, probability=T, 
                         kernel="radial", gamma=gamma, cost=cost)                        
           }
           prob = predict(model, newdata=test.set, probability=T)
           prob = attr(prob,"probabilities")
           #print(cbind(prob,as.character(test.set$y)))
           #print(dim(prob))
           prob = prob[,which(colnames(prob)==1)]/rowSums(prob)
           prob
         },
         ada = {
           model = ada(Total~., data = train.set)
           prob = predict(model, newdata=test.set, type='probs')
           #print(cbind(prob,as.character(test.set$y)))
           prob = prob[,2]/rowSums(prob)
           prob
         }
  ) 
}
```


```{r}
pre.test <- function(dataset, cl.name, r=0.5, prob.cutoff=0.7) {
  ## Let's use 70% random sample as training and remaining as testing
  ## by default use 0.5 as cut-off
  n.obs <- nrow(dataset) # no. of observations in dataset
  n.train = floor(n.obs*r)
  train.idx = sample(1:n.obs,n.train)
  train.idx
  train.set = dataset[train.idx,]
  test.set = dataset[-train.idx,]
  cat('pre-test',cl.name,':',
      '#training:',nrow(train.set),
      '#testing',nrow(test.set),'\n')
  prob = do.classification(train.set, test.set, cl.name)
  # prob is an array of probabilities for cases being positive
  
  ## get confusion matrix
  predicted = as.numeric(prob > prob.cutoff)
  actual = test.set$Total
  confusion.matrix = table(actual,predicted)
  error = (confusion.matrix[1,2]+confusion.matrix[2,1]) / nrow(test.set)  
  cat('error rate:',error,'\n')
  # you may compute other measures based on confusion.matrix
  # @see handout03 p.32-36
}
```

```{r}
err=dim(6)
precision=dim(6)
recall=dim(6)
fscore=dim(6)
auc=dim(6)
a=1
k.fold.cv <- function(dataset, cl.name, k.fold=10, prob.cutoff=0.7) {
  ## default: 10-fold CV, cut-off 0.5 
n.obs <- nrow(dataset) # no. of observations
  s = sample(n.obs)
  errors = dim(k.fold)
  probs = NULL
  actuals = NULL
  for (k in 1:k.fold) 
  {
    test.idx = which(s %% k.fold == (k-1) ) # use modular operator
    train.set = dataset[-test.idx,]
    test.set = dataset[test.idx,]    
    cat(k.fold,'-fold CV run',k,cl.name,':',
        '#training:',nrow(train.set),
        '#testing',nrow(test.set),'\n')
    prob = do.classification(train.set, test.set, cl.name)
    predicted = as.numeric(prob > prob.cutoff)
    actual = test.set$Total
    confusion.matrix = table(actual,predicted)
    confusion.matrix
    error = (confusion.matrix[1,2]+confusion.matrix[2,1]) / nrow(test.set)  
    errors[k] = error
    cat('\t\terror=',error,'\n')
    probs = c(probs,prob)
    actuals = c(actuals,actual)
    ## you may compute other measures and store them in arrays
  }
  avg.error = mean(errors)
  cat(k.fold,'-fold CV results:','avg error=',avg.error,'\n')
  
  ## plot ROC
  result = data.frame(probs,actuals)
  pred = prediction(result$probs,result$actuals)
  perf = performance(pred, "tpr","fpr")
  plot(perf)  
  
  ## get other measures by using 'performance'
  get.measure <- function(pred, measure.name='auc') {
    perf = performance(pred,measure.name)
    m <- unlist(slot(perf, "y.values"))
#     print(slot(perf, "x.values"))
#     print(slot(perf, "y.values"))
    m
  }
  err[a] <<- mean(get.measure(pred, 'err'))
  precision[a] <<- mean(get.measure(pred, 'prec'),na.rm=T)
  recall[a] <<- mean(get.measure(pred, 'rec'),na.rm=T)
  fscore[a] <<- mean(get.measure(pred, 'f'),na.rm=T)
  cat('error=',err[a],'precision=',precision[a],'recall=',recall[a],'f-score',fscore[a],'\n')
  auc[a] <<- get.measure(pred, 'auc')
  cat('auc=',auc[a],'\n')
  a<<-a+1
}
```

```{r}
my.classifier <- function(dataset, cl.name, do.cv) {
  n.obs <- nrow(dataset) # no. of observations in dataset
  n.cols <- ncol(dataset) # no. of predictors
  cat('my dataset:',
      n.obs,'observations',
      n.cols-1,'predictors','\n')
  print(dataset[1:3,])
  cat('label (Total) distribution:')
  print(table(dataset$Total))
  
  pre.test(dataset, cl.name)
  if (do.cv) k.fold.cv(dataset, cl.name)
}

```


```{r}
load.data.task <- function() {
  dataframe=read.csv("pokemon.csv",header = T) #load file in dataframe
  dataframe=dataframe[-1]
  dataframe=dataframe[-1]
  dataframe$Total=recode(dataframe$Total,"'>500'=1;else=0")
  dataframe$Legendary=recode(dataframe$Legendary,"'TRUE'=1;else=0")
  dataframe$Type.1=recode(dataframe$Type.1,"'Bug'=1;'Dark'=2;'Dragon'=3;'Electric'=4;'Fairy'=5;'Fighting'=6;'Fire'=7;'Ghost'=8;'Grass'=9;'Ground'=10;'Ice'=11;'Normal'=12;'Poison'=13;'Psychic'=14;'Rock'=15;'Steel'=16;'Water'=17;'Flying'=18")
  dataframe$Type.2=recode(dataframe$Type.2,"'Bug'=1;'Dark'=2;'Dragon'=3;'Electric'=4;'Fairy'=5;'Fighting'=6;'Fire'=7;'Ghost'=8;'Grass'=9;'Ground'=10;'Ice'=11;'Normal'=12;'Poison'=13;'Psychic'=14;'Rock'=15;'Steel'=16;'Water'=17;'NO'=18;'Flying'=19")
  return(dataframe)
}
```


```{r}
### main ###
dataset = load.data.task()
dataset = na.omit(dataset)
my.classifier(dataset, cl.name='knn',do.cv=T)
# cl.name can take 'lr','knn','nb','dtree','svm','ada'
```

```{r}
### main ###
my.classifier(dataset, cl.name='lr',do.cv=T)
# cl.name can take 'lr','knn','nb','dtree','svm','ada'
```

```{r}
### main ###
my.classifier(dataset, cl.name='nb',do.cv=T)
# cl.name can take 'lr','knn','nb','dtree','svm','ada'
```

```{r}
### main ###
my.classifier(dataset, cl.name='dtree',do.cv=T)
# cl.name can take 'lr','knn','nb','dtree','svm','ada'
```

```{r}
### main ###
my.classifier(dataset, cl.name='svm',do.cv=T)
# cl.name can take 'lr','knn','nb','dtree','svm','ada'
```

```{r}
### main ###
my.classifier(dataset, cl.name='ada',do.cv=T)
# cl.name can take 'lr','knn','nb','dtree','svm','ada'
```

```{r}
df=data.frame(err,precision,recall,fscore,auc)
rownames(df) <- c("knn", "lr", "nb", "dtree", "svm", "ada")
print(df)
```

```{r}
ggplot(data=df, aes(x=c("knn", "lr", "nb", "dtree", "svm", "ada"),y=auc)) + 
  geom_bar(stat = "identity")+labs(x = "classifier Name")
```

```{r}
ggplot(data=df, aes(x=c("knn", "lr", "nb", "dtree", "svm", "ada"),y=fscore)) + 
  geom_bar(stat = "identity")+labs(x = "classifier Name")
```

